## mybatis-plus
mybatis-plus:
  typeAliasesPackage: github.sjroom.dop.resource.bean.entity
  #配置mybaits自定义类型转换类所在的包
  type-handlers-package: github.sjroom.resource.center.handler

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
